# Compose file for development

name: "scala-dining-webapp"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DINING_DEBUG: "true"
      DINING_SECRET_KEY: hallo
      DINING_ALLOWED_HOSTS: "*"
      DINING_DATABASE_URL: postgres://dining:dining@db/dining
      DINING_SITE_BANNER: "Development"
    depends_on:
      - db
    volumes:
      - .:/app/src
    ports:
      - 8000:8000

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: dining
      POSTGRES_PASSWORD: dining
      POSTGRES_DB: dining
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
