# Generated by Django 2.1.3 on 2019-02-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0002_auto_20190203_2324"),
        ("dining", "0002_auto_20190203_2149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="DiningList",
            name="association",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="userdetails.Association",
                unique_for_date="date",
            ),
        ),
    ]
