# Generated by Django 2.1.5 on 2019-02-11 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0003_auto_20190203_2324"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dininglist",
            name="dinner_cost_keep_single_constant",
        ),
        migrations.RemoveField(
            model_name="dininglist",
            name="dinner_cost_total",
        ),
        migrations.RenameField(
            model_name="dininglist",
            old_name="dinner_cost_single",
            new_name="dining_cost",
        ),
    ]
