# Generated by Django 2.1.3 on 2019-02-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0004_auto_20190211_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningcomment",
            name="message",
            field=models.CharField(max_length=256),
        ),
    ]
