# Generated by Django 2.1.3 on 2019-02-26 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dining", "0005_auto_20190221_2339"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiningCommentView",
            new_name="DiningCommentVisitTracker",
        ),
    ]
