# Generated by Django 2.1.3 on 2019-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0006_auto_20190226_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dininglist",
            name="dish",
            field=models.CharField(
                blank=True, default="", help_text="The dish made", max_length=100
            ),
        ),
    ]
