# Generated by Django 2.2 on 2019-05-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0007_auto_20190423_1651"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiningDayAnnouncements",
            new_name="DiningDayAnnouncement",
        ),
        migrations.AlterField(
            model_name="dininglist",
            name="date",
            field=models.DateField(),
        ),
    ]
