# Generated by Django 2.2 on 2019-05-13 13:05

from django.db import migrations


def move_claimant_purchaser(apps, schema_editor):
    DiningList = apps.get_model("dining", "DiningList")
    for dl in DiningList.objects.all():
        dl.owners.add(dl.claimed_by)
        if dl.purchaser:
            dl.owners.add(dl.purchaser)


def move_back(apps, schema_editor):
    DiningList = apps.get_model("dining", "DiningList")
    for dl in DiningList.objects.all():
        dl.claimed_by = dl.owners.first()


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0013_auto_20190513_1505"),
    ]

    operations = [
        migrations.RunPython(move_claimant_purchaser, move_back, elidable=True)
    ]
