# Generated by Django 2.2.5 on 2019-10-11 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0016_auto_20190514_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dininglist',
            name='main_contact',
        ),
        migrations.RemoveField(
            model_name='dininglist',
            name='purchaser',
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='owners',
            field=models.ManyToManyField(help_text='Owners can manage the dining list.', related_name='owned_dining_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
