# Generated by Django 2.2.15 on 2020-08-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0017_auto_20200824_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningentry',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='creditmanagement.Transaction'),
        ),
    ]
