# Generated by Django 2.2.6 on 2019-10-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0017_auto_20191012_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dininglist',
            name='min_diners',
        ),
    ]
