# Generated by Django 3.1.7 on 2021-03-20 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0018_auto_20210319_2310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dininglist",
            name="main_contact",
        ),
        migrations.RemoveField(
            model_name="dininglist",
            name="purchaser",
        ),
    ]
