# Generated by Django 2.2.6 on 2019-10-12 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dining', '0018_remove_dininglist_min_diners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininglist',
            name='dish',
            field=models.CharField(blank=True, default='', help_text='The dish made.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='max_diners',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(12)], verbose_name='maximum diners'),
        ),
    ]
