# Generated by Django 3.2.13 on 2022-12-24 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0019_auto_20210320_1309"),
        # We need to make sure that the allergies have been copied over before we delete the UserDiningSettings model.
        ("userdetails", "0022_move_allergies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDiningSettings",
        ),
    ]
