# Generated by Django 3.2.7 on 2021-10-19 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0019_auto_20210320_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dininglist',
            name='auto_pay',
        ),
        migrations.RemoveField(
            model_name='dininglist',
            name='min_diners',
        ),
        migrations.AddField(
            model_name='dininglist',
            name='cancelled_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='max_diners',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userdiningsettings',
            name='allergies',
            field=models.CharField(blank=True, help_text='Leave empty if not applicable.', max_length=100, verbose_name='allergies or dietary restrictions'),
        ),
    ]
