# Generated by Django 3.2.8 on 2021-10-22 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0020_auto_20211019_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diningwork',
            old_name='has_cleaned',
            new_name='has_cleaned_old',
        ),
        migrations.RenameField(
            model_name='diningwork',
            old_name='has_cooked',
            new_name='has_cooked_old',
        ),
        migrations.RenameField(
            model_name='diningwork',
            old_name='has_shopped',
            new_name='has_shopped_old',
        ),
        migrations.RemoveField(
            model_name='diningentry',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='dininglist',
            name='dining_cost',
        ),
        migrations.RemoveField(
            model_name='dininglist',
            name='payment_link',
        ),
        migrations.AddField(
            model_name='diningentry',
            name='external_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='adjustable_duration',
            field=models.DurationField(default=datetime.timedelta(days=2), help_text='How long a dining list can be adjusted after its date.'),
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='dish',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='limit_signups_to_association_only',
            field=models.BooleanField(default=False, help_text='Whether only members of the given association can sign up.'),
        ),
    ]
