# Generated by Django 3.2.13 on 2023-01-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0020_delete_userdiningsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReminderLock",
            fields=[
                (
                    "dining_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="dining.dininglist",
                    ),
                ),
                ("sent", models.DateTimeField(null=True)),
            ],
        ),
    ]
