# Generated by Django 3.2.8 on 2021-10-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0021_auto_20211022_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningentry',
            name='has_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningentry',
            name='has_cooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diningentry',
            name='has_shopped',
            field=models.BooleanField(default=False),
        ),
    ]
