# Generated by Django 3.2.13 on 2022-12-25 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0021_create_paymentreminderlock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diningwork",
            old_name="has_cleaned",
            new_name="has_cleaned_old",
        ),
        migrations.RenameField(
            model_name="diningwork",
            old_name="has_cooked",
            new_name="has_cooked_old",
        ),
        migrations.RenameField(
            model_name="diningwork",
            old_name="has_shopped",
            new_name="has_shopped_old",
        ),
    ]
