# Generated by Django 3.2.13 on 2022-12-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0022_rename_old_help_stats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diningentry",
            options={"verbose_name_plural": "dining entries"},
        ),
        migrations.AddField(
            model_name="diningentry",
            name="external_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="diningentry",
            name="has_cleaned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningentry",
            name="has_cooked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningentry",
            name="has_shopped",
            field=models.BooleanField(default=False),
        ),
    ]
