# Generated by Django 3.2.8 on 2021-10-22 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0023_move_help_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dininglist',
            name='max_diners',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
