# Generated by Django 3.2.13 on 2022-12-25 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0024_move_help_stats_data"),
    ]

    operations = [
        # For some reason these RemoveField didn't work properly.
        # But I think that they are not necessary.
        # migrations.RemoveField(
        #     model_name='diningentryuser',
        #     name='diningentry_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='diningentryuser',
        #     name='diningwork_ptr',
        # ),
        migrations.DeleteModel(
            name="DiningEntryExternal",
        ),
        migrations.DeleteModel(
            name="DiningEntryUser",
        ),
        migrations.DeleteModel(
            name="DiningWork",
        ),
    ]
