# Generated by Django 3.2.8 on 2021-10-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0024_alter_dininglist_max_diners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningentryuser',
            name='diningentry_ptr',
        ),
        migrations.RemoveField(
            model_name='diningentryuser',
            name='diningwork_ptr',
        ),
        migrations.DeleteModel(
            name='DiningEntryExternal',
        ),
        migrations.DeleteModel(
            name='DiningEntryUser',
        ),
        migrations.DeleteModel(
            name='DiningWork',
        ),
    ]
