# Generated by Django 4.1.4 on 2023-03-07 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dining", "0025_remove_dining_entry_subclasses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diningcomment",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="diningcomment",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
