# Generated by Django 3.2.8 on 2021-10-25 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0026_delete_userdiningsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningentry',
            name='dining_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='dining.dininglist'),
        ),
    ]
