# Generated by Django 3.2.8 on 2022-02-13 17:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0027_alter_diningentry_dining_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diningentry',
            options={'verbose_name_plural': 'dining entries'},
        ),
        migrations.RemoveField(
            model_name='dininglist',
            name='cancelled_reason',
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='max_diners',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dininglist',
            name='serve_time',
            field=models.TimeField(default=datetime.time(18, 0), validators=[django.core.validators.MinValueValidator(datetime.time(16, 30), message="Kitchen can't be used this early."), django.core.validators.MaxValueValidator(datetime.time(19, 30), message="Kitchen can't be used this late.")]),
        ),
    ]
