# Generated by Django 5.0 on 2024-01-05 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dining", "0028_alter_dininglist_payment_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diningcomment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="diningcomment",
            name="email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether an e-mail notification was sent for this comment.",
            ),
        ),
        migrations.AlterField(
            model_name="diningcomment",
            name="dining_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="dining.dininglist",
            ),
        ),
        migrations.AlterField(
            model_name="diningcomment",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
