# Generated by Django 5.0 on 2024-12-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dining", "0030_dininglist_dish_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dininglist",
            name="dish_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not specified"),
                    ("meat", "🍗 With meat"),
                    ("fish", "🐟 With fish"),
                    ("vegetarian", "🥕 Vegetarian"),
                    ("vegan", "🌿 Vegan"),
                    ("meat_or_vegetarian", "Meat or vegetarian"),
                    ("meat_or_vegan", "Meat or vegan"),
                ],
                max_length=20,
                verbose_name="kind of dish",
            ),
        ),
        migrations.AlterField(
            model_name="dininglist",
            name="limit_signups_to_association_only",
            field=models.BooleanField(
                default=False,
                help_text="Whether only members of the given association can sign up.",
                verbose_name="association only",
            ),
        ),
    ]
