# Generated by Django 2.1.3 on 2019-02-03 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0002_auto_20190203_2324"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="related_user",
        ),
        migrations.DeleteModel(
            name="UserDetail",
        ),
    ]
