# Generated by Django 2.1.3 on 2019-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0003_auto_20190204_0025"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_link",
            field=models.CharField(default="", editable=False, max_length=150),
        ),
    ]
