# Generated by Django 2.1.3 on 2019-03-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0008_remove_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
