# Generated by Django 2.1.3 on 2019-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0009_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
