# Generated by Django 2.1.3 on 2019-04-29 11:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0010_auto_20190304_2050"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOverview",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("userdetails.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="association",
            name="is_min_exception",
            field=models.BooleanField(default=False),
        ),
    ]
