# Generated by Django 2.1.5 on 2019-04-29 15:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0010_auto_20190304_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOverview',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('UserDetails.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='association',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
