# Generated by Django 2.1.5 on 2019-04-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0012_auto_20190429_1306'),
        ('UserDetails', '0011_auto_20190429_1748'),
    ]

    operations = [
    ]
