# Generated by Django 2.2 on 2019-04-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0012_auto_20190429_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='external_link',
        ),
    ]
