# Generated by Django 2.2.8 on 2020-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0017_association_balance_update_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="has_site_stats_access",
            field=models.BooleanField(default=False),
        ),
    ]
