# Generated by Django 2.2.15 on 2020-08-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0018_association_has_site_stats_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="has_min_exception",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this association has an exception to the minimum balance.",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="is_choosable",
            field=models.BooleanField(
                default=True,
                help_text="If checked, this association can be chosen as membership by users.",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="social_app",
            field=models.ForeignKey(
                blank=True,
                help_text="A user automatically becomes member of the association if they sign up using this social app.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="socialaccount.SocialApp",
            ),
        ),
    ]
