# Generated by Django 2.1.5 on 2019-08-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetails', '0018_auto_20190803_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'permissions': [('has_suspended_user_screen', 'Whether this association can see the suspended users'), ('has_system_credit_screen', 'Whether this association can watch the system balance screen')]},
        ),
    ]
