# Generated by Django 3.2.8 on 2021-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0020_auto_20210319_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_grocery_payments',
            field=models.BooleanField(default=True, help_text='Whether to allow automatic grocery payments from your account balance. You will always be notified and can always undo these transactions.'),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_requirements',
            field=models.CharField(blank=True, help_text='E.g. gluten or vegetarian. Leave empty if not applicable.', max_length=100, verbose_name='food allergies or preferences'),
        ),
    ]
