# Generated by Django 3.2.13 on 2022-12-24 12:47

from django.db import migrations


def forwards(apps, schema_editor):
    UserDiningSettings = apps.get_model('dining', 'UserDiningSettings')

    for obj in UserDiningSettings.objects.all():
        user = obj.user
        user.allergies = obj.allergies
        user.save()


def backwards(apps, schema_editor):
    UserDiningSettings = apps.get_model('dining', 'UserDiningSettings')
    User = apps.get_model('userdetails', 'User')

    for obj in User.objects.all():
        UserDiningSettings.objects.create(user=obj, allergies=obj.allergies)


class Migration(migrations.Migration):
    dependencies = [
        ('userdetails', '0021_auto_20221224_1346'),
        # We need to make sure that the UserDiningSettings model exists, we depend on it.
        ('dining', '0019_auto_20210320_1309'),
    ]

    operations = [
        # We do not provide reverse_code, so the migration is irreversible.
        migrations.RunPython(forwards, backwards, elidable=True)
    ]
