# Generated by Django 3.2.8 on 2021-10-23 13:10
import warnings

from django.db import migrations


def move_forward(apps, schema_editor):
    UserDiningSettings = apps.get_model('dining', 'UserDiningSettings')

    for obj in UserDiningSettings.objects.all():
        user = obj.user
        user.dietary_requirements = obj.allergies
        user.save()


# Backwards is not implemented, requires creating new UserDiningSettings instances
# def move_backward(apps, schema_editor):
#     pass

class Migration(migrations.Migration):
    dependencies = [
        ('userdetails', '0021_auto_20211023_1509'),
        ('dining', '0025_auto_20211023_0053'),  # For UserDiningSettings
    ]

    operations = [
        migrations.RunPython(move_forward, elidable=True),
    ]
