# Generated by Django 3.2.8 on 2021-10-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0023_auto_20211025_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='allow_invoicing',
            field=models.BooleanField(default=False, help_text='If checked, members can upgrade their balance by having the association invoice them.'),
        ),
    ]
