# Generated by Django 4.1.4 on 2023-12-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdetails", "0023_alter_user_allergies"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="short_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="association",
            name="slug",
            field=models.SlugField(help_text="The slug is used in URLs."),
        ),
    ]
