# Generated by Django 3.2.8 on 2021-10-28 15:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0024_alter_association_allow_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_public',
            field=models.BooleanField(default=False, help_text='If selected, your e-mail address will be visible to other diners.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='If given, will be visible to other diners.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail address'),
        ),
    ]
