# Generated by Django 3.2.8 on 2021-10-31 14:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0025_auto_20211028_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOverview',
        ),
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ('slug',)},
        ),
        migrations.RenameField(
            model_name='usermembership',
            old_name='is_verified',
            new_name='verified_state',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_public',
            field=models.BooleanField(default=False, help_text='If selected, your e-mail address will be visible to other diners on the same list.', verbose_name='e-mail public'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='If given, will be visible to other diners on the same list.', max_length=128, region=None),
        ),
    ]
