# Generated by Django 5.0 on 2024-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdetails", "0025_delete_useroverview_user_allergen_celery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="allergen_celery",
            field=models.BooleanField(default=False, verbose_name="celery"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_crustaceans",
            field=models.BooleanField(default=False, verbose_name="crustaceans"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_egg",
            field=models.BooleanField(default=False, verbose_name="egg"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_fish",
            field=models.BooleanField(default=False, verbose_name="fish"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_gluten",
            field=models.BooleanField(default=False, verbose_name="gluten"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_lupin",
            field=models.BooleanField(default=False, verbose_name="lupin"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_milk",
            field=models.BooleanField(default=False, verbose_name="milk"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_molluscs",
            field=models.BooleanField(default=False, verbose_name="molluscs"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_mustard",
            field=models.BooleanField(default=False, verbose_name="mustard"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_nuts",
            field=models.BooleanField(default=False, verbose_name="nuts"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_peanuts",
            field=models.BooleanField(default=False, verbose_name="peanuts"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_sesame",
            field=models.BooleanField(default=False, verbose_name="sesame"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_soya",
            field=models.BooleanField(default=False, verbose_name="soya"),
        ),
        migrations.AlterField(
            model_name="user",
            name="allergen_sulphite",
            field=models.BooleanField(default=False, verbose_name="sulphite"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="e-mail address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="food_preferences",
            field=models.CharField(
                blank=True,
                help_text="Vegetarian, vegan or other food preferences.",
                max_length=200,
                verbose_name="preferences",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="other_allergy",
            field=models.CharField(
                blank=True,
                help_text="If you have an other allergy not listed above, enter it here.",
                max_length=200,
                verbose_name="other allergies",
            ),
        ),
    ]
