# Generated by Django 3.2.8 on 2021-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0026_auto_20211031_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='verified_on',
            new_name='verified_last_change',
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='verified_state',
            field=models.BooleanField(null=True),
        ),
    ]
