# Generated by Django 5.0 on 2024-12-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdetails", "0026_alter_user_allergen_celery_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="A user with this e-mail address will be shown a notice indicating that their e-mail address is invalid.",
                        max_length=254,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
