# Generated by Django 3.2.8 on 2021-10-31 16:26

from django.db import migrations


def forward(apps, schema_editor):
    UserMembership = apps.get_model('userdetails', 'UserMembership')
    UserMembership.objects.filter(verified_state=False, verified_last_change=None).update(verified_state=None)


class Migration(migrations.Migration):
    dependencies = [
        ('userdetails', '0027_auto_20211031_1612'),
    ]

    operations = [
        migrations.RunPython(forward, elidable=True),
    ]
