# Generated by Django 3.2.8 on 2022-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0028_move_verified_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='invoicing_description',
            field=models.TextField(blank=True, help_text='Description of how members will be invoiced. For Q-bill it will be something like "twice a year the amount will be deducted from your bank account using direct debit."'),
        ),
        migrations.AlterField(
            model_name='association',
            name='invoicing_method',
            field=models.CharField(blank=True, help_text="Name of the invoicing method. For instance 'Q-bill' in the case of Quadrivium.", max_length=100),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='verified_last_change',
            field=models.DateTimeField(null=True),
        ),
    ]
