# Generated by Django 3.2.8 on 2022-02-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0029_auto_20220210_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allow_grocery_payments',
        ),
    ]
