# Generated by Django 3.2.8 on 2022-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0030_remove_user_allow_grocery_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='invoicing_method',
            field=models.CharField(blank=True, help_text="Name of the invoicing method. For instance 'Q-bill' in the case of Quadrivium.", max_length=100, verbose_name='invoicing method name'),
        ),
    ]
