# Generated by Django 3.2.8 on 2021-10-23 21:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dining', '0026_delete_userdiningsettings'),
        ('creditmanagement', '0014_auto_20210320_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='groceries cost per person')),
                ('payment_link', models.URLField(blank=True, help_text='Payment link, e.g. Tikkie or ING Payment Request.')),
                ('phone_number', models.CharField(blank=True, help_text='This may make it easier to contact you for payment issues.', max_length=100)),
                ('include_email', models.BooleanField(default=True, help_text='Include your account e-mail in the message to all diners.', verbose_name='include e-mail')),
                ('remarks', models.CharField(blank=True, help_text="For instance an IBAN number if you can't provide a payment link.", max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dining_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dining.dininglist')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='groceries.payment')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='creditmanagement.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
