# Generated by Django 3.2.8 on 2021-10-24 22:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cost',
            new_name='cost_pp',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default='0.01', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total groceries cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymententry',
            name='external_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='include_email',
            field=models.BooleanField(default=True, help_text='Include your account e-mail address in the message to all diners.', verbose_name='include e-mail'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, help_text="E.g. Tikkie or ING Payment Request. Tip: use a payment link with variable amount, then you won't need to change it the next time."),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='This makes it easier to contact you for payment issues.', max_length=100),
        ),
    ]
