# Generated by Django 3.2.8 on 2021-11-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_auto_20211025_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymententry',
            options={'ordering': ('external_name', 'user__first_name', 'user__last_name')},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='include_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
    ]
