# Generated by Django 3.2.8 on 2022-02-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0003_auto_20211102_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allow_transaction',
            field=models.BooleanField(default=True, help_text="If you don't want to receive payments in your account balance and only want to receive payments in cash via the payment link, disable this option.", verbose_name='allow payment using a transaction to your account balance'),
        ),
    ]
