# Generated by Django 2.1.5 on 2019-04-14 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_auto_20190227_1203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteupdate",
            name="version",
        ),
    ]
