# Generated by Django 3.2.8 on 2022-02-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_siteupdate_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUpdate',
        ),
    ]
