# Generated by Django 3.2.8 on 2022-02-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_delete_siteupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisitTracker',
        ),
    ]
