# Generated by Django 2.1.5 on 2019-02-03 18:23

import datetime
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userdetails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingDiningTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Money transferred",
                    ),
                ),
                ("order_moment", models.DateTimeField(default=datetime.datetime.now)),
                ("confirm_moment", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FixedTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Money transferred",
                    ),
                ),
                ("order_moment", models.DateTimeField(default=datetime.datetime.now)),
                ("confirm_moment", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PendingDiningListTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Money transferred",
                    ),
                ),
                ("order_moment", models.DateTimeField(default=datetime.datetime.now)),
                ("confirm_moment", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "source_association",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pendingtransaction_transaction_source",
                        to="userdetails.Association",
                        verbose_name="The association giving the money",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="source_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pendingtransaction_transaction_source",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user giving the money",
            ),
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="target_association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pendingtransaction_transaction_target",
                to="userdetails.Association",
                verbose_name="The association recieving the money",
            ),
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pendingtransaction_transaction_target",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user receiving the money",
            ),
        ),
    ]
