# Generated by Django 2.1.5 on 2019-02-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dining", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userdetails", "0001_initial"),
        ("creditmanagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingdininglisttracker",
            name="dining_list",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="dining.DiningList"
            ),
        ),
        migrations.AddField(
            model_name="fixedtransaction",
            name="source_association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixedtransaction_transaction_source",
                to="userdetails.Association",
                verbose_name="The association giving the money",
            ),
        ),
        migrations.AddField(
            model_name="fixedtransaction",
            name="source_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixedtransaction_transaction_source",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user giving the money",
            ),
        ),
        migrations.AddField(
            model_name="fixedtransaction",
            name="target_association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixedtransaction_transaction_target",
                to="userdetails.Association",
                verbose_name="The association recieving the money",
            ),
        ),
        migrations.AddField(
            model_name="fixedtransaction",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fixedtransaction_transaction_target",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user receiving the money",
            ),
        ),
    ]
