# Generated by Django 2.1.2 on 2018-10-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserDetails', '0001_initial'),
        ('CreditManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_source', to='UserDetails.Association', verbose_name='The association giving the money'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_source', to=settings.AUTH_USER_MODEL, verbose_name='The user giving the money'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_target', to='UserDetails.Association', verbose_name='The association recieving the money'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_target', to=settings.AUTH_USER_MODEL, verbose_name='The user receiving the money'),
        ),
        migrations.AddField(
            model_name='associationcredit',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserDetails.Association'),
        ),
    ]
