# Generated by Django 2.1.5 on 2019-02-03 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creditmanagement", "0002_auto_20190203_1923"),
    ]

    operations = []
