# Generated by Django 2.1.5 on 2019-01-22 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userdetails", "0001_initial"),
        ("creditmanagement", "0004_auto_20190203_2324"),
    ]

    operations = []
