# Generated by Django 2.2 on 2020-08-17 10:30

from django.db import migrations, models
from General.db_view_migration import DeleteView, CreateView
from django.conf import settings
from decimal import Decimal
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('CreditManagement', '0009_usercredit_view_update'),
    ]

    operations = [
        DeleteView(
            name='UserCredit',
        ),

        migrations.AlterField(
            model_name='fixedtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Money transferred'),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Money transferred'),
        ),

        CreateView(
            name='UserCredit',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(blank=True, db_column='balance', decimal_places=2, max_digits=6, null=True)),
                ('balance_fixed', models.DecimalField(blank=True, db_column='balance_fixed', decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
