# Generated by Django 2.2 on 2020-08-16 19:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditManagement', '0009_usercredit_view_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Money transferred'),
        ),
        migrations.AlterField(
            model_name='pendingtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Money transferred'),
        ),
    ]
