# Generated by Django 2.2.15 on 2020-08-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditmanagement', '0012_auto_20200824_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='source_association',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='source_user',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='target_association',
        ),
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='target_user',
        ),
        migrations.AlterField(
            model_name='account',
            name='special',
            field=models.CharField(choices=[('kitchen_cost', 'Kitchen cost'), ('generic', 'Generic')], default=None, max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='FixedTransaction',
        ),
        migrations.DeleteModel(
            name='PendingTransaction',
        ),
    ]
