# Generated by Django 3.1.7 on 2021-03-19 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("creditmanagement", "0013_auto_20210319_2310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingtransaction",
            name="source_association",
        ),
        migrations.RemoveField(
            model_name="pendingtransaction",
            name="source_user",
        ),
        migrations.RemoveField(
            model_name="pendingtransaction",
            name="target_association",
        ),
        migrations.RemoveField(
            model_name="pendingtransaction",
            name="target_user",
        ),
        migrations.DeleteModel(
            name="FixedTransaction",
        ),
        migrations.DeleteModel(
            name="PendingTransaction",
        ),
    ]
