# Generated by Django 3.1.7 on 2022-04-28 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userdetails", "0020_auto_20210319_2310"),
        ("creditmanagement", "0014_auto_20210320_0015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="association",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="userdetails.association",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="special",
            field=models.CharField(
                blank=True,
                choices=[("kitchen_cost", "Kitchen cost")],
                default=None,
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
